#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/essential'

rr = Essential::RoundRobin.new

commands = %w[ls]
options  = %w[-d -l]
files    = %w[Gemfile Rakefile]

rr.generate_combinations(commands, options, files) do |combination|
  <<-COMBIEOF
# GENERATED BY Essential::RoundRobin#generate_combinations
#{combination.join(' ')}

  COMBIEOF
end

Dir.glob('output/*').map { |file| puts File.read(file) }
